import mongoose, { Schema, Document } from "mongoose";

export interface IBudgetItem {
  name: string;
  estimatedCost: number;
  actualCost: number;
}

export interface IBudget extends Document {
  eventId: Schema.Types.ObjectId;
  items: IBudgetItem[];
  status: 'draft' | 'committeeReview' | 'approved' | 'locked';
  autoGeneratedReport?: string;
  createdBy: Schema.Types.ObjectId;
  approvedBy?: Schema.Types.ObjectId;
  createdAt: Date;
  updatedAt: Date;
}

const BudgetSchema = new Schema<IBudget>({
  eventId: { type: Schema.Types.ObjectId, ref: 'Event', required: true },
  items: [{
    name: { type: String, required: true },
    estimatedCost: { type: Number, default: 0 },
    actualCost: { type: Number, default: 0 }
  }],
  status: { 
    type: String, 
    enum: ['draft', 'committeeReview', 'approved', 'locked'], 
    default: 'draft' 
  },
  autoGeneratedReport: String,
  createdBy: { type: Schema.Types.ObjectId, ref: 'User', required: true },
  approvedBy: { type: Schema.Types.ObjectId, ref: 'User' },
  createdAt: { type: Date, default: Date.now },
  updatedAt: { type: Date, default: Date.now }
});

export default mongoose.models.Budget || mongoose.model<IBudget>("Budget", BudgetSchema);